In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[2])
print(arr[1:4])

print(arr + 10)
print(arr * 2)

print(np.mean(arr))
print(np.sum(arr))

3
[2 3 4]
[11 12 13 14 15]
[ 2  4  6  8 10]
3.0
15
