In [2]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.ones(5)
arr3 = np.arange(10)

print(arr)
print(type(arr))
print(arr + 10) #can work with operators unlike a list
print(arr[:4])
print(arr[3:4])
print(arr[2:])
print(arr2)
print(arr3 *2)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[11 12 13 14 15]
[1 2 3 4]
[4]
[3 4 5]
[1. 1. 1. 1. 1.]
[ 0  2  4  6  8 10 12 14 16 18]


In [12]:
#same size array can be added too
a = np.array([1, 2, 3])

b = np.array([10, 20, 30])

print(a+b)

print(a.mean())
print(a.max())
print(a.min())
print(a.sum())

[11 22 33]
2.0
3
1
6
