In [3]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))
print(arr + 10) #can work with operators unlike a list
print(arr[:4])
print(arr[3:4])
print(arr[2:])


[1 2 3 4 5]
<class 'numpy.ndarray'>
[11 12 13 14 15]
[1 2 3 4]
[4]
[3 4 5]


In [ ]:
#same size array can be added too
a = np.array([1, 2, 3])

b = np.array([10, 20, 30])

print(a+b)

print(a.mean())
print(a.max())
print(a.min())
print(a.sum())

[11 22 33]


AttributeError: 'numpy.ndarray' object has no attribute 'info'