In [ ]:
import numpy as np

#understanding vector
employee = np.array([25, 50000, 2])

print("Employee data:", employee)


Employee data: [   25 50000     2]


In [4]:
employees = np.array([[25, 50000, 2], [30, 60000, 5], [28, 55000, 3]])
print("employees \n", employees)

employees 
 [[   25 50000     2]
 [   30 60000     5]
 [   28 55000     3]]


In [5]:
age_experience = np.array([25, 2])
weights = np.array([0.5, 2])

result = np.dot(age_experience, weights)
print("Result of dot product:", result)

Result of dot product: 16.5


In [6]:
A = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dot(A, b)
print("result of dot product of A and b:\n", result)


result of dot product of A and b:
 [[19 22]
 [43 50]]
