# Importing the library

In [1]:
import numpy as np

# Array Creation

In [8]:
data = np.array([1,2,3])
data1 = np.array([[1,2,3], [4,5,6]])

print(f'1D array: {data}')
print(' ')
print(f'2D array: \n{data1}')
print('\nCreated array using the array function.')

1D array: [1 2 3]
 
2D array: 
[[1 2 3]
 [4 5 6]]

Created array using the array function.


In [13]:
print(f'{np.zeros((3,2))}')
print('\nCreated array using the zeros function.')

[[0. 0.]
 [0. 0.]
 [0. 0.]]

Created array using the zeros function.


In [14]:
print(f'{np.ones((3,2))}')
print('\nCreated array using the ones function.')

[[1. 1.]
 [1. 1.]
 [1. 1.]]

Created array using the ones function.


In [15]:
print(f'{np.arange(0,11,1)}')
print('\nCreated array using the arange function.')

[ 0  1  2  3  4  5  6  7  8  9 10]

Created array using the arange function.


In [18]:
print(f'{np.linspace(0,5,3)}')
print('\nCreated array using the linespace function.')

[0.  2.5 5. ]

Created array using the linespace function.


# Indexing in array

In [7]:
print(f'First element of the 1D array is: {data[0]}')
print(f'Last element of the 1D array is: {data[-1]}')
print(f'Middle element of the 1D array is: {data[1:2][0]}')

First element of the 1D array is: 1
Last element of the 1D array is: 3
Middle element of the 1D array is: 2


In [21]:
print(f'First element of the 2D array: {data1[0][0]}')
print(f'Last element of the 2D array: {data1[1][2]}')

First element of the 2D array: 1
Last element of the 2D array: 6


# Broadcasting the Array

In [22]:
print(f'Brodacasting the 1D array by adding {2} in each element inside the array {data}, the result is: {2 + data}')

Brodacasting the 1D array by adding 2 in each element inside the array [1 2 3], the result is: [3 4 5]


In [28]:
print(f'Brodacasting the 2D array by multiplying the each element inside the array \n{data1} by {2}, \nthe result is: \n{2 + data1}')

Brodacasting the 2D array by multiplying the each element inside the array 
[[1 2 3]
 [4 5 6]] by 2, 
the result is: 
[[3 4 5]
 [6 7 8]]


# Vectorized OPS

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b 
print(f'Vectorized addition between the {a} and {b}, the result is: {c}')

Vectorized addition between the [1 2 3] and [4 5 6], the result is: [5 7 9]


In [31]:
arr = np.array([1, 2, 3, 4])

result = arr * 2  # Output: [2, 4, 6, 8]
print(f'Vectorized multiplication (multiplies each element by 2 instantly, the result is: {result}')

squared_roots = np.sqrt(arr)
print(f'Vectorized math function, the result is: {squared_roots}')

Vectorized multiplication (multiplies each element by 2 instantly, the result is: [2 4 6 8]
Vectorized math function, the result is: [1.         1.41421356 1.73205081 2.        ]


# Successfully completed the task 1.